
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorJson;

/** CUP generated class containing symbol constants. */
public class Parser_JsonSym {
  /* terminals */
  public static final int LLAVE_IZQ = 4;
  public static final int DECIMAL = 7;
  public static final int COMA = 5;
  public static final int LLAVE_DER = 3;
  public static final int DOSPUT = 2;
  public static final int EOF = 0;
  public static final int COMILLAS = 6;
  public static final int NOMBRE_DATO = 8;
  public static final int error = 1;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DOSPUT",
  "LLAVE_DER",
  "LLAVE_IZQ",
  "COMA",
  "COMILLAS",
  "DECIMAL",
  "NOMBRE_DATO"
  };
}

